// templates/preact/src/index.tsx
import { computed, signal } from '@preact/signals'
import { render } from 'preact'

import './style.scss'

function App() {
  const count = signal(0)
  const double = computed(() => count.value * 2)

  return (
    <div className="card">
      <h1 className="title">Hello World</h1>
      <button onClick={() => count.value++}>
        {count} x 2 = {double}
      </button>
    </div>
  )
}

const fragment = document.createDocumentFragment()
render(<App />, fragment)
document.body.appendChild(fragment)

// templates/solid/src/index.tsx
import { createMemo, createSignal } from 'solid-js'
import { render } from 'solid-js/web'
import type { Component } from 'solid-js'

import './style.scss'

const App: Component = () => {
  const [count, setCount] = createSignal(2)
  const double = createMemo(() => count() * 2)

  return (
    <div class="card">
      <h1 class="title">Hello World</h1>
      <button onClick={() => setCount(count() + 1)}>
        {count()} x 2 = {double()}
      </button>
    </div>
  )
}

const fragment = document.createDocumentFragment()
render(() => <App />, fragment)
document.body.appendChild(fragment)
